### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by sorinr** [amanuel2/ng-forum#13]
## After registration
- [ ] The user should receive a mail with the link for confirming their email address
- [ ] After the user is confirming their email address they should be ported to the login page and display a message that email was confirmed and now they could log in.
- [ ] on the login page it should be a remember me checkbox

**Comment by amanuel2** [comment]
@sorinr for your third issue.. it automatically rememebers you. And i set it to remember you for about 5 dayish... About the two other issues ima work on that

**Comment by sorinr** [comment]
@amanuel2 It is bad practice to auto-remember user credentials unless his opting for this. that's why i say a remember me button is needed. If you are already logged-in its another thing.

**Comment by amanuel2** [comment]
@sorinr i dont know if firebase supports non-auto remember me credentials... I will post an issue there! Thanks for the tips!

**Comment by combsco** [comment]
Auto-remember me isn't a firebase issue.

If the user doesn't want to be auto-logged in or remember they should be able to opt-out. Simple as a check to see if the user has clicked "Remember me" on the login form and storing that value.

**Comment by amanuel2** [comment]
@combsco im preety sure i remember,  the time i can control session time.. so im decently sure it has to do with firebase. Are you sure?

**Comment by combsco** [comment]
Example...
If I clicked ... "Remember Me" then you would set...something like:

```
var ref = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
ref.authWithPassword({
  email    : "bobtony@firebase.com",
  password : "correcthorsebatterystaple"
}, function(error, authData) { /* Your Code */ }, {
  remember: "default"
});
```

However, if I didn't click the button then you would...

```
var ref = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
ref.authWithPassword({
  email    : "bobtony@firebase.com",
  password : "correcthorsebatterystaple"
}, function(error, authData) { /* Your Code */ }, {
  remember: false
});
```

Its pretty much in your code... somewhere

```
IF RememberMe is checked then... push to Firebase with Remember: 30 days
ELSE set remember to False
```

https://www.firebase.com/docs/security/simple-login-email-password.html

**Comment by amanuel2** [comment]
@combsco hmm... Thanks a lot! I didnt know about that feautre! One question though. does it have to be 30 days? Cant you change it?

**Comment by amanuel2** [comment]
@sorinr Confirmation of Email is same as Recaptcha. We will get this done in New Release!

**Comment by sorinr** [comment]
@amanuel2 Confirmation of email is needed and its not the same as Recaptcha. Think of this scenario: when registering, a user can give not his real email address but the email of somebody else just to flood him in with a lot of unwanted mail. It is just an important security issue. It has to be done now not with the next release.

**Comment by amanuel2** [comment]
To anyone who was concerned or wanted to know if we have this. Yes we have fixed in new release coming soon
