### ISSUE TITLE
Firefox Icons Issue

### ISSUE THREAD

**Issue by amanuel2** [amanuel2/ng-forum#17]
We have realized there is a Firefox Icons Issue. It will be fixed in the next release coming soon, With Many Changes!

**Comment by amanuel2** [comment]
Solved in new release 0.8.0! :boom:

**Comment by amanuel2** [comment]
Hs

**Comment by jdc20181** [comment]
I have looked at it and i personally don't see any issues with the icons, of course we have came a long way since this issue came about but, i dont see it. So no need to keep it open!
