### ISSUE TITLE
Just a clarification

### ISSUE THREAD

**Issue by karuppiah7890** [amanuel2/ng-forum#2]
I see so many words with the spelling "Fourum" and "Fourm". But the repo is named properly as "forum". So, what is the name actually ? Is it a typo or the name is "Fourum" / "Fourm" in a stylish way ? Because even the image says "Fourm".

![image](https://camo.githubusercontent.com/01ba871845de2f238cdba545dde7e1c799bcb629/687474703a2f2f692e696d6775722e636f6d2f4a6855415a56682e6a7067)

Just a clarification.

**Comment by Someguy123** [comment]
I think it's a typo, I don't think the creator is native english (or is dyslexic), there are many typos, or just mis-spellings throughout the README

**Comment by karuppiah7890** [comment]
I thought the same. Is not native english. But the image...that's why I asked.

**Comment by Someguy123** [comment]
@karuppiah7890 you can tell even by the last sentence on that page that the image isn't exactly perfect quality either, "Meet the creators that touches your creative heart" (that's slightly broken english right there)

**Comment by karuppiah7890** [comment]
Hmm....

**Comment by amanuel2** [comment]
Guys im back sorry...But i make so many typos. Sorry @karuppiah7890  @Someguy123

**Comment by amanuel2** [comment]
Ill try to fix all my typos. And actually previously i use to think it was actually fourm :laughing:
