### ISSUE TITLE
.gitignore - Where art thou?

### ISSUE THREAD

**Issue by combsco** [amanuel2/ng-forum#20]
This repository needs a [.gitignore](https://www.gitignore.io/) file because I see a lot of garbage.

Also how do these folders/files relate to the project and are they necessary?
- .idea
- Stackoverflow/Randomizer
- c9
- git

**Comment by amanuel2** [comment]
Idk what a .gitignore is.... can you consider adding a pull-request please? Thankyou

**Comment by combsco** [comment]
You should probably look it up and become familiar... or you're going to pollute future projects with stuff we don't need/care about.

**Comment by jdc20181** [comment]
here: https://help.github.com/articles/ignoring-files/

**Comment by amanuel2** [comment]
@combsco  @jdc20181 i dont know how to put a .gitignore manually..

**Comment by jdc20181** [comment]
just ceate a new file in name put .gitignore and it should have some templates you can choose

**Comment by amanuel2** [comment]
Solved,  now this issue is a very needed solution! 

https://github.com/amanuel2/ng-forum/issues/28

**Comment by nasr18** [comment]
gitingore , wont upload unwanted things to github.

**Comment by nasr18** [comment]
just create a file named '.gitignore' and define what files and folder you dont want to upload and download while push and fetch from github.

**Comment by jdc20181** [comment]
Thanks Nasr....

**Comment by amanuel2** [comment]
Fixed!
