### ISSUE TITLE
Email Confirmation- Need it only once!

### ISSUE THREAD

**Issue by jdc20181** [amanuel2/ng-forum#27]
Issue: Sends 2 confirmation emails.....For passwordss...

**Comment by amanuel2** [comment]
Nope that dosent happen. Please provide a screenshot. closing until then...

**Comment by jdc20181** [comment]
ughi wouldnt have made a issue if not....

**Comment by jdc20181** [comment]
http://screenshot.sh/oAGm8toSAz328

**Comment by nasr18** [comment]
yeah its very annoying. i got 269 spam mail regarding authentication.

**Comment by amanuel2** [comment]
Dupiclcate #28
