### ISSUE TITLE
"Invalid Callback URL" when logging in or registering with GitHub 

### ISSUE THREAD

**Issue by sorianog** [amanuel2/ng-forum#30]
When I click the GitHub icon at http://ng-forum.site88.net/#/auth to log in or register, I see the following popup: 

![image](https://cloud.githubusercontent.com/assets/13261711/15872156/a1dc551e-2cbd-11e6-823f-7168d48938bb.png)

Looks like it is prompting to check for the application's configuration as specified here:
https://www.firebase.com/docs/web/guide/login/github.html#section-configure

**Comment by amanuel2** [comment]
Thanks a lot, for this. I accidently linked the callback to our Dev Firebase... Ill have to create a new Github and Twitter Application For Dev mode. Again, thanks a bunch for pointing this out. Now this is fixed and shouldnt be an issue. If you see any other issues, please tell us that. Dont worry about the design though, we are surely making it material one step at a time :wink:  .
