### ISSUE TITLE
Many gramatical errors in README

### ISSUE THREAD

**Issue by Gip-Gip** [amanuel2/ng-forum#39]
While going through the README I noticed many grammatical errors, some of which can confuse the reader (or at least me). I'm working on a refined version of the README but I encourage someone to beat me to it.

**Comment by amanuel2** [comment]
@Gip-Gip right now i am working on an Operating System. Its cool if you can help that too , when it starts.. Right now we are still learning osdev : https://github.com/Bone-Project/BoneOS .

**Comment by jdc20181** [comment]
Like amanuel said hes currently working on another project, I will look at it and see if there is something I can fix. It was pretty much thrown together to get the point across, if you are like me you can decipher the errors into what it could be using context clues. Thanks for noticing though :)

**Comment by jdc20181** [comment]
I fixed the errors that I could see. Hope it helps :)
