### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by haylinmoore** [amanuel2/ng-forum#8]
There is no wiki!

**Comment by amanuel2** [comment]
You are right we need a wiki

**Comment by amanuel2** [comment]
Sorry what is a wiki again? :package:

**Comment by haylinmoore** [comment]
wi·ki
ˈwikē/
noun
a website that allows collaborative editing of its content and structure by its users.

Or we just need a documentation

**Comment by amanuel2** [comment]
@herohamp this is not a libary.. i cant have a documentation. This is an actual Website, and uses diffrent types of libaraies

**Comment by haylinmoore** [comment]
Ok never mind

**Comment by amanuel2** [comment]
This issue has gone downhill.. therefore i will close it.
